import { faEnvelope } from '@fortawesome/free-regular-svg-icons';
import { faPhone } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React from 'react';
import '../styles/CV.scss';

const getEducationElements = (educations, placeholder) => {
  const toProcess = educations.length === 0 ? placeholder : educations;
  return toProcess.map((education) => {
    return (
      <li key={education.id}>
        <h3 className="title-of-study">{education.titleOfStudy}</h3>
        <p className="school-name">{education.schoolName}</p>
        <p className="duration">
          {education.fromYear} - {education.toYear}
        </p>
      </li>
    );
  });
};

const getWorkExperienceElements = (workExperiences, placeholder) => {
  const toProcess =
    workExperiences.length === 0 ? placeholder : workExperiences;
  return toProcess.map((workExperience) => {
    return (
      <li key={workExperience.id}>
        <h3 className="position-title">{workExperience.positionTitle}</h3>
        <p className="company-name">{workExperience.companyName}</p>
        <p className="duration">
          {workExperience.fromYear} - {workExperience.toYear}
        </p>
        {workExperience.mainTasks.length === 0 || <h4>Main Tasks</h4>}
        {workExperience.mainTasks.length === 0 || (
          <ul>
            {workExperience.mainTasks.map((task) => {
              return (
                <li key={task.id}>
                  <span className="bullet">&gt;</span>
                  {task.task}
                </li>
              );
            })}
          </ul>
        )}
      </li>
    );
  });
};

function CV({ data, refProp }) {
  const educations = getEducationElements(
    data.educations,
    data.placeholder.educations
  );

  const workExperiences = getWorkExperienceElements(
    data.workExperiences,
    data.placeholder.workExperiences
  );

  return (
    <div className="cv printable" ref={refProp}>
      <section className="personal-details">
        <h1>
          {data.firstName || data.placeholder.firstName}{' '}
          {data.lastName || data.placeholder.lastName}
        </h1>
        <p className="email">
          <FontAwesomeIcon icon={faEnvelope} />
          {data.email || data.placeholder.email}
        </p>
        <p className="phone-number">
          <FontAwesomeIcon icon={faPhone} />
          {data.phoneNumber || data.placeholder.phoneNumber}
        </p>
      </section>
      <section className="education">
        <h2>Education</h2>
        <ul>{educations}</ul>
      </section>
      <section className="work-experience">
        <h2>Work Experience</h2>
        <ul>{workExperiences}</ul>
      </section>
      <footer>
        <p>Generated by CV Builder</p>
      </footer>
    </div>
  );
}

export default React.forwardRef((props, ref) => (
  <CV refProp={ref} {...props} />
));
