import { faEnvelope } from '@fortawesome/free-regular-svg-icons';
import { faPhone } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import React from 'react';
import '../styles/CV.scss';

const MM_PER_16PX = 127 / 30;

class CV extends React.Component {
  constructor(props) {
    super(props);
    this.cv = React.createRef();
  }

  updateRemSize = () => {
    const { width } = this.cv.current.getBoundingClientRect();
    const pixelPerMM = width / 210;
    const currentRemSize = MM_PER_16PX * pixelPerMM;

    this.cv.current.style.fontSize = `${currentRemSize}px`;
  };

  render() {
    return (
      <div className="cv" ref={this.cv}>
        <section className="personal-details">
          <h1>Zekumoru Dragonhart</h1>
          <p className="email">
            <FontAwesomeIcon icon={faEnvelope} />
            dev@zekumoru.com
          </p>
          <p className="phone-number">
            <FontAwesomeIcon icon={faPhone} />
            +12 123 456 7890
          </p>
        </section>
        <section className="education">
          <h2>Education</h2>
          <ul>
            <li>
              <h3 className="title-of-study">Some Degree</h3>
              <p className="school-name">Some University</p>
              <p className="duration">2023 - 2023</p>
            </li>
            <li>
              <h3 className="title-of-study">Some Degree</h3>
              <p className="school-name">Some University</p>
              <p className="duration">2023 - 2023</p>
            </li>
            <li>
              <h3 className="title-of-study">Some Degree</h3>
              <p className="school-name">Some University</p>
              <p className="duration">2023 - 2023</p>
            </li>
          </ul>
        </section>
        <section className="work-experience">
          <h2>Work Experience</h2>
          <ul>
            <li>
              <h3 className="position-title">Some Position</h3>
              <p className="company-name">Some Company</p>
              <p className="duration">2023 - 2023</p>
              <h4>Main Tasks</h4>
              <ul>
                <li>
                  <span className="bullet">&gt;</span>Task A
                </li>
                <li>
                  <span className="bullet">&gt;</span>Task B
                </li>
                <li>
                  <span className="bullet">&gt;</span>Task C
                </li>
              </ul>
            </li>
            <li>
              <h3 className="position-title">Some Position</h3>
              <p className="company-name">Some Company</p>
              <p className="duration">2023 - 2023</p>
              <h4>Main Tasks</h4>
              <ul>
                <li>
                  <span className="bullet">&gt;</span>Task A
                </li>
                <li>
                  <span className="bullet">&gt;</span>Task B
                </li>
                <li>
                  <span className="bullet">&gt;</span>Task C
                </li>
              </ul>
            </li>
            <li>
              <h3 className="position-title">Some Position</h3>
              <p className="company-name">Some Company</p>
              <p className="duration">2023 - 2023</p>
              <h4>Main Tasks</h4>
              <ul>
                <li>
                  <span className="bullet">&gt;</span>Task A
                </li>
                <li>
                  <span className="bullet">&gt;</span>Task B
                </li>
                <li>
                  <span className="bullet">&gt;</span>Task C
                </li>
              </ul>
            </li>
          </ul>
        </section>
        <footer>
          <p>Generated by CV Builder</p>
        </footer>
      </div>
    );
  }

  componentDidMount() {
    this.updateRemSize();
    window.addEventListener('resize', this.updateRemSize);
  }

  componentWillUnmount() {
    window.removeEventListener('resize', this.updateRemSize);
  }
}

export default CV;
